### ISSUE TITLE
添加獭窝可下载的配置文件—go-cqhttp

### ISSUE THREAD

**Issue by yimo0908** [Bluefissure/OtterBot#102]
文件名称：`config.hjson`
内容：
```
{
    uin: 0
    password: ""
    encrypt_password: false
    password_encrypted: ""
    enable_db: true
    access_token: ""
    relogin: {
        enabled: true
        relogin_delay: 3
        max_relogin_times: 0
    }
    _rate_limit: {
        enabled: false
        frequency: 1
        bucket_size: 1
    }
    ignore_invalid_cqcode: false
    force_fragmented: false
    heartbeat_interval: 5
    http_config: {
        enabled: false
        host: 0.0.0.0
        port: 5700
        timeout: 0
        post_urls: {}
    }
    ws_config: {
        enabled: false
        host: 0.0.0.0
        port: 6700
    }
    ws_reverse_servers: [
        {
            enabled: true
            reverse_url: 
            reverse_api_url: ""
            reverse_event_url: ""
            reverse_reconnect_interval: 3000
        }
    ]
    post_message_format: string
    use_sso_address: false
    debug: false
    log_level: ""
    web_ui: {
        enabled: true
        host: 127.0.0.1
        web_ui_port: 9999
        web_input: false
    }
}

```
其中
`uin`对应qq号  
`password`对应qq密码（下载后自己填）
`access_token` 对应獭獭的token
`reverse_url`对应獭窝的WS Universal 地址，如`ws://bot.pencilss.top/ws`

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/OtterBot/commit/230b4d98269305b0f284e0076f7c34b5663b64ea 可以进行一下测试能否正常连接。

**Comment by yimo0908** [comment]
> [230b4d9](https://github.com/Bluefissure/OtterBot/commit/230b4d98269305b0f284e0076f7c34b5663b64ea) 可以进行一下测试能否正常连接。

line 181出错，`post_urls:`后的花括号并没有在文件中生成，导致go-cqhttp配置读取失败，拒绝启动

**Comment by Bluefissure** [comment]
> > [230b4d9](https://github.com/Bluefissure/OtterBot/commit/230b4d98269305b0f284e0076f7c34b5663b64ea) 可以进行一下测试能否正常连接。
> 
> line 181出错，`post_urls:`后的花括号并没有在文件中生成，导致go-cqhttp配置读取失败，拒绝启动

https://github.com/Bluefissure/OtterBot/commit/c25353113774d014b5239b98c399cf4fde5a7e89 PS：这配置格式就离谱。
