### ISSUE TITLE
如果在网站后台以超级账户登陆，返回网站首页后会报错

### ISSUE THREAD

**Issue by SnowMoonSS** [Bluefissure/OtterBot#106]
使用docker部署的獭窝，在控制台下添加超级账户后，以超级账户登陆獭窝后台，返回獭窝首页就会报错：https://dpaste.com/76Y9T2TXV
清除浏览器cookies就能正常访问
我怀疑是獭窝后台记录了超级账户的cookies，返回獭窝后在自己的数据库中找不到这个账户……

**Comment by Bluefissure** [comment]
需要去 /admin/ffxivbot/qquser/ 找到对应的QQ号绑定dbuser

**Comment by SnowMoonSS** [comment]
> 需要去 /admin/ffxivbot/qquser/ 找到对应的QQ号绑定dbuser

非常感谢，问题解决了
