### ISSUE TITLE
獭爹獭爹，能否开放一个图库上传api（和closed那个略有不同）

### ISSUE THREAD

**Issue by ClayLivince** [Bluefissure/OtterBot#108]
现在的图库存放方式是将图片的url、key、category、时间、上传者什么的存进数据库，所以图片上传的时候只需要一个图片的url就好了，那么可以开放一个api，让他我的注册用户调用api,传入图片的url存入数据库就行了，不用占用主窝的上传api量，图片上传我们自己搞定之后直接发url过来保存这样可以嘛？
我现在的窝的实现是，在主窝上注册了一个账户，然后调取api来获得图片。如果能够这样上传的话，没有图片的小窝也可以搞到一些图片了！感谢獭爹！

**Comment by Bluefissure** [comment]
首先主窝的上传是VIP套餐，基本不会有上传量限制。
另外没太搞懂这个API的目的是什么，批量导入图片到你自己的窝吗？

**Comment by ClayLivince** [comment]
是想把图片上传到主窝的数据库里面，因为自己的窝用的人很少，也没有什么图，所以获取图片是从主窝调用的图。如果能把这边上传的图片直接上传到主窝的话，应该会方便一点这样子，图库也大概能活跃一点（？（呃就是主窝接受外部传图进图库

**Comment by Bluefissure** [comment]
感觉开放上传可能带来一些权限相关的问题（因为对应的机器人和领养者不在这个窝所以一旦上传就没有正常方法删除）
退而求其次可以先实现一个本地图库和远程图库的功能，本地图库可以上传，远程图库只能查看（虽然似乎你已经以某种方法实现了）

**Comment by ClayLivince** [comment]
好的好的，獭爹辛苦啦！
