### ISSUE TITLE
环境配置中出的小问题以及创建超级管理员的一个小bug

### ISSUE THREAD

**Issue by kirablood** [Bluefissure/OtterBot#109]
作者大大你好，这是我第一次发issues请见谅，而且我也是一知半解的程度，可能出错的问题是因为我自己憨批，请不要生气。

以下是我折腾了一个星期发现的一些问题（最后我使用了docker配置并成功运行）

首先是数据库初始化中的迁移数据库，直接运行python manage.py ******（省略）后会出现
 File "manage.py", line 14
   ) form exc
          ^
SyntaxError: invalid syntax

如果使用python3 manage.py *****（省略）会出现更多的报错

后面发现我在使用docker配置的情况下先使用这条命令docker exec -t -i otterbot-web /bin/bash 后再运行python manage.py *****（省略）就可以正常使用了

还有一个问题是我在使用docker配置完后创建超级管理员，按照步骤创建完成怎么登陆都提示登录失败！用户名或密码错误！我确定用户名、邮箱和密码都没有出错，因为我创建了5个账号一个都登录不上，应该是bug了，请作者大大看一下。

其他的一些小问题就是1.环境配置中没有提到安装Django；
2.国内网络环境太难下载Pyenv的一键脚本了，基本连不上（可能云服务器连得上，我自家电信是连不上），作者大大可以考虑改成以下命令安装。

git clone https://github.com/pyenv/pyenv.git ~/.pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile
exec "$SHELL"
pyenv install 3.*.*

3.项目Clone里的安装依赖使用的pip无法使用（找不到pip命令），需要pip3才可以；
4.RabbitMQ安装还是官网的好用一些，我用的步骤是以下命令，作者大大可以看看，如果没问题的话可以直接更新到wiki里（？）

sudo apt-get install -y erlang-base erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssl erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

wget -O - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo apt-key add -

sudo apt-get update -y

sudo apt-get install curl gnupg -y

curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -

sudo apt-get install apt-transport-https

sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list <<EOF
deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
deb https://dl.bintray.com/rabbitmq/debian bionic main
EOF

sudo apt-get update -y

sudo apt-get install rabbitmq-server -y --fix-missing

service rabbitmq-server start

service rabbitmq-server status

最后感谢作者大大能看完，如果觉得我写的有用的话就好，如果有什么需要帮忙的话可以联系我（不过基本不懂，只会用的类型）

**Comment by Bluefissure** [comment]
docker肯定要进入到docker里才能操作，docker和host是隔离开的，在外面无论如何运行命令都无法正常访问。
管理员创建失败我也不清楚是为什么，检查一下登陆时是否把邮箱当作用户名了，没有问题就进入到数据库里面手动看一下auth_user表。
1. Django 在 requirements.txt 里。
2. 在国内的特殊网络环境下遇到下载安装软件的问题都可以通过百度或挂梯子解决。
3. 如果安装了python 2.* 版本的话 pip 一般是python2的，此时 pip3 才是python3的，这些都可以自行修改。
4. wiki里写了可以按照官网的安装指南进行安装，由于不同系统和环境安装方法不同我觉得没必要抄一份到指南中。

**Comment by kirablood** [comment]
注册时候用户名是admin 邮箱是我qq邮箱 密码重复两次，登录时强制要用邮箱登录，会提示要加@，不然不让登录，如果超级管理员账号是 域名/admin 的Django的账号就没事了。。。数据库那里我就不懂了，好像没这个管理账号也问题不大，能用就行（

**Comment by Bluefissure** [comment]
> 注册时候用户名是admin 邮箱是我qq邮箱 密码重复两次，登录时强制要用邮箱登录，会提示要加@，不然不让登录，如果超级管理员账号是 域名/admin 的Django的账号就没事了。。。数据库那里我就不懂了，好像没这个管理账号也问题不大，能用就行（
网站的登录是邮箱登录，后台/admin登录是用户名登录。

**Comment by kirablood** [comment]
好的，谢谢作者大大，我的问题都问完了，感谢作者大大写的项目，机器人超好用（
