### ISSUE TITLE
希望隐藏机器人后，领养人也能一并隐藏掉

### ISSUE THREAD

**Issue by SnowMoonSS** [Bluefissure/OtterBot#121]
最近老有奇怪的人通过账号查找加我好友……包括但不限于卖片的，邀请游戏内测的（多半是诈骗），看见机器人是隐藏的但还是不死心想要用的……

**Comment by Bluefissure** [comment]
Resolved in https://github.com/Bluefissure/OtterBot/commit/d66ffb083d8bb435597a4cc7276cc6450381cfd3

**Comment by Bluefissure** [comment]
Resolved in https://github.com/Bluefissure/OtterBot/commit/d66ffb083d8bb435597a4cc7276cc6450381cfd3

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/OtterBot/commit/d66ffb083d8bb435597a4cc7276cc6450381cfd3
