### ISSUE TITLE
P站的Imjad API已失效，建议作者更换为HibiAPI 

### ISSUE THREAD

**Issue by chawaa** [Bluefissure/OtterBot#122]
1. 项目地址：https:// github.com/mixmoe/HibiAPI 

- 支持heroku免费部署

- [手动部署](https://github.com/mixmoe/HibiAPI/wiki/Deployment)

- [API文档地址](https://api.obfs.dev/docs#tag/Pixiv) 

2. pixiv.moe也有现成API，pixiv.moe的作者大大多次公开表示过可以免费使用。https:// api.pixiv.moe [API文档地址](https://api.kotori.love/docs/#/pixiv)

**Comment by Bluefissure** [comment]
谢谢告知！之后会按照对应文档更新！
