### ISSUE TITLE
Upgrade to new trace.moe API

### ISSUE THREAD

**Issue by soruly** [Bluefissure/OtterBot#127]
Hi, just want to notify you the new trace.moe API is out.
Please take a look and update your program, otherwise it will be broken when the old API deprecates.
You can find the docs of the new API with migration guide at https://github.com/soruly/trace.moe-api

**Comment by Bluefissure** [comment]
Thanks for acknoledging me! I've already updated to the new version of API.
It's glad to see an image url parameter in the new api :)
