### ISSUE TITLE
[指令]quest命令不会返回最精确的匹配结果

### ISSUE THREAD

**Issue by sandtechnology** [Bluefissure/OtterBot#128]
In：
```
/quest 暗之战士
```
Expect：
![6P 9J3SOI5P HXUOHQ@%FYM](https://user-images.githubusercontent.com/20417547/120018580-f316b880-c019-11eb-9f00-9c45c77ef732.png)

Actual：
```
来自暗之战士的鼓励
支线任务
https://ff14.huijiwiki.com/wiki/%E4%BB%BB%E5%8A%A1%3A%E6%9D%A5%E8%87%AA%E6%9A%97%E4%B9%8B%E6%88%98%E5%A3%AB%E7%9A%84%E9%BC%93%E5%8A%B1
```

**Comment by Bluefissure** [comment]
resolved in https://github.com/Bluefissure/OtterBot/commit/fe61b19c92248a2deb444a87748bb059a66d8ec8
