### ISSUE TITLE
Websocket连接出错

### ISSUE THREAD

**Issue by fakedestinyck** [Bluefissure/OtterBot#152]
最近bot一直出现
`Websocket连接出错, 可能被服务器关闭, 将在3秒后重试连接, Host: xn--v9x.net:443-Client-Universal Path: /ws`
是出什么问题了吗

**Comment by Bluefissure** [comment]
持续被ddos攻击中

**Comment by fakedestinyck** [comment]
> 持续被ddos攻击中

啊居然 怎么会这样0 0先star了祝快点结束orz

**Comment by Bluefissure** [comment]
应该已经恢复了
