### ISSUE TITLE
event_handler在调用group on_notice存在异常

### ISSUE THREAD

**Issue by f0re1gnKey** [Bluefissure/OtterBot#154]
刚invite进入的群并没有在数据库里create，导致get找不到对象

https://github.com/Bluefissure/OtterBot/blob/34f450d7e90d5179b5c94c722cbfd74d53a11162/ffxivbot/event_handler.py#L378

**Comment by Bluefissure** [comment]
Fixed https://github.com/Bluefissure/OtterBot/commit/49b12430ac08216b86b1a8cb8bce4cade0994c7a
