### ISSUE TITLE
Docker搭建的窝不能查询DPS

### ISSUE THREAD

**Issue by hundunzhidian** [Bluefissure/OtterBot#155]
原因：
ffxivbot/handlers/QQUtils.py文件下 281行
```
    redis_client = redis.Redis(host="localhost", port=6379, decode_responses=True)
```
对于docker-compose部署的方式来说，localhost代表这个容器，无法获取到redis信息导致查询失败，改成
```
    redis_client = redis.Redis(host="redis", port=6379, decode_responses=True)
```
就可以了，如果是其他方式部署，则需要把localhost改成redis的监听地址

**Comment by Bluefissure** [comment]
忘了加 sed，已修改
https://github.com/Bluefissure/OtterBot/commit/e1be6fd990dbc644b34c2d89b360bafc4602246b
