### ISSUE TITLE
使用“/hh” 指令时无法正确显示图片

### ISSUE THREAD

**Issue by IcEater** [Bluefissure/OtterBot#164]
排查了一下，应该是因为在拼接字符串时遇到了None值，抛出错误的Exception，中断了正常流程。
修改后的代码如下，我在本地测试应该能解决问题，还请帮忙确认一下修改的逻辑是否符合预期

这个是修改的Pull Request： https://github.com/Bluefissure/OtterBot/pull/163

**Comment by Bluefissure** [comment]
感谢！https://github.com/Bluefissure/OtterBot/pull/163
