### ISSUE TITLE
[Tips] 在最近发布的 django 4.1 中，新添加的 CONN_HEALTH_CHECKS 应该能解决 mysql server gone away 的问题

### ISSUE THREAD

**Issue by sandtechnology** [Bluefissure/OtterBot#179]
> CONN_HEALTH_CHECKS
> New in Django 4.1.
> Default: False
> If set to True, existing [persistent database connections](https://docs.djangoproject.com/en/4.1/ref/databases/#persistent-database-connections) will be health checked before they are reused in each request performing database access. If the health check fails, the connection will be reestablished without failing the request when the connection is no longer usable but the database server is ready to accept and serve new connections (e.g. after database server restart closing existing connections).

就是目前还没有升级到django 4.1所以我没法发PR（
不过我自己的窝已经先更新过去用上了 希望问题能解决（

Ref:
https://docs.djangoproject.com/en/4.1/ref/databases/#persistent-database-connections
https://docs.djangoproject.com/en/4.1/ref/settings/#conn-health-checks

**Comment by Bluefissure** [comment]
THX! https://github.com/Bluefissure/OtterBot/commit/41eaab700573a0bbebae87dd9dd5752fd8fe0baf

**Comment by sandtechnology** [comment]
> THX! [41eaab7](https://github.com/Bluefissure/OtterBot/commit/41eaab700573a0bbebae87dd9dd5752fd8fe0baf)

好像加错了x，这个是在数据库连接设置下的 CONN_HEALTH_CHECKS
然后django最新版本是4.1.1

**Comment by sandtechnology** [comment]
确实是加错的 这个是database下的（
![image](https://user-images.githubusercontent.com/20417547/188934259-2576a701-fe72-45cb-83a0-3b1b32212b32.png)

**Comment by Bluefissure** [comment]
woshibendan
https://github.com/Bluefissure/OtterBot/commit/dd05ba185628d85dce49f31224b0a2fc59a98a46

**Comment by Bluefissure** [comment]
> 然后django最新版本是4.1.1

似乎我这里的 pypi 还获取不到 4.1.1，前天才发布（
