### ISSUE TITLE
Docker搭建的窝无法正常运行

### ISSUE THREAD

**Issue by FirstMelody** [Bluefissure/OtterBot#183]
docker搭建的窝会显示mysql版本过低,手动更新则会导致其他问题.

otterbot-web    | Internal Server Error: /
otterbot-web    | Traceback (most recent call last):
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
otterbot-web    |     response = get_response(request)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
otterbot-web    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
otterbot-web    |   File "/FFXIVBOT/./ffxivbot/views/tata.py", line 406, in tata
otterbot-web    |     for bot in bots:
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__
otterbot-web    |     self._fetch_all()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1866, in _fetch_all
otterbot-web    |     self._result_cache = list(self._iterable_class(self))
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
otterbot-web    |     results = compiler.execute_sql(
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1393, in execute_sql
otterbot-web    |     cursor = self.connection.cursor()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
otterbot-web    |     return self._cursor()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
otterbot-web    |     self.ensure_connection()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
otterbot-web    |     self.connect()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 265, in connect
otterbot-web    |     self.init_connection_state()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 257, in init_connection_state
otterbot-web    |     super().init_connection_state()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 232, in init_connection_state
otterbot-web    |     self.check_database_version_supported()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 207, in check_database_version_supported
otterbot-web    |     raise NotSupportedError(
otterbot-web    | django.db.utils.NotSupportedError: MySQL 5.7 or later is required (found 5.6.51).
otterbot-web    | 2022-09-21 22:35:07,501 ERROR    Internal Server Error: /
otterbot-web    | Traceback (most recent call last):
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
otterbot-web    |     response = get_response(request)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
otterbot-web    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
otterbot-web    |   File "/FFXIVBOT/./ffxivbot/views/tata.py", line 406, in tata
otterbot-web    |     for bot in bots:
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 394, in __iter__
otterbot-web    |     self._fetch_all()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1866, in _fetch_all
otterbot-web    |     self._result_cache = list(self._iterable_class(self))
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
otterbot-web    |     results = compiler.execute_sql(
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1393, in execute_sql
otterbot-web    |     cursor = self.connection.cursor()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
otterbot-web    |     return self._cursor()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
otterbot-web    |     self.ensure_connection()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
otterbot-web    |     self.connect()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
otterbot-web    |     return func(*args, **kwargs)
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 265, in connect
otterbot-web    |     self.init_connection_state()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 257, in init_connection_state
otterbot-web    |     super().init_connection_state()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 232, in init_connection_state
otterbot-web    |     self.check_database_version_supported()
otterbot-web    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 207, in check_database_version_supported
otterbot-web    |     raise NotSupportedError(
otterbot-web    | django.db.utils.NotSupportedError: MySQL 5.7 or later is required (found 5.6.51).

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/OtterBot/commit/8c2a0bdf557195f7dc3c55babe1c803e38a395a8

**Comment by Bluefissure** [comment]
经测试改成5.7就可以了，如果有其他问题请提交新的ticket
