### ISSUE TITLE
Quest查询任务群聊无反馈

### ISSUE THREAD

**Issue by Nothunpple** [Bluefissure/OtterBot#189]
![image](https://user-images.githubusercontent.com/31199261/207040872-25fb894b-4f71-402d-82d9-a7cffde85a7a.png)
改为文本兼容模式后可以发送出，是卡片api坏了还是有关键词触发被夹了呀

**Comment by Bluefissure** [comment]
卡片被夹了

**Comment by Nothunpple** [comment]
> 

草，明白了 感谢www
