### ISSUE TITLE
关于獭窝在大陆地区无法直连的问题

### ISSUE THREAD

**Issue by Marciy** [Bluefissure/OtterBot#203]
目前大陆部分地区尝试直连或者内地代理访问獭窝（https://xn--v9x.net/） 时偶尔会出现无法访问的情况，bot在尝试连接獭窝的时候也会提示
![`KRDXXCHNEXC%2N8)B0B$9](https://github.com/Bluefissure/OtterBot/assets/69225653/4f0aadf0-be44-4b08-8229-abd66c953cb2)
如果想要继续保持bot运行的话是需要在开启框架的时候对框架单独设置一个代理吗？
还是凭运气测试连接？

**Comment by Bluefissure** [comment]
被CF波及到了，暂时回源应该能解决一部分连接问题。
之后可能迁移至水獭云cdn。
