### ISSUE TITLE
是否考虑把image del的权限扩大到主人可以删除通过所属机器人上传的任意图

### ISSUE THREAD

**Issue by NepPure** [Bluefissure/OtterBot#98]
这样可以方便管理，快速干掉一些不适宜的图

**Comment by Bluefissure** [comment]
目前似乎没有记录图片是通过哪个机器人上传的，所以暂时无法确定对应的机器人主人。

**Comment by NepPure** [comment]
)新增字段 √
）以前的无视 x

**Comment by Bluefissure** [comment]
实现了 https://github.com/Bluefissure/OtterBot/commit/439cdaa9d5f9f0820297d80f8df242f1e793621f
